tasks:
  - init: gem install shopify-cli
    command: shopify login --store 
ports:
  - name: Shopify CLI
    description: Login Port
    port: 3456
    onOpen: ignore
  - name: Theme
    description: Local Theme Preview
    port: 9292
    onOpen: open-browser