image:
  file: .gitpod.Dockerfile
tasks:
  - command: shopify login --store https://true-work-digital-sandbox.myshopify.com/admin
ports:
  - name: Shopify CLI
    description: Login Port
    port: 3456
    onOpen: ignore
  - name: Theme
    description: Local Theme Preview
    port: 9292
    onOpen: open-browser